name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # Until we implement these platforms, comment this out
        # platform: [ ubuntu-latest, macos-latest, windows-latest ]
        platform: [ ubuntu-latest ]
        toolchain: [ stable, nightly, 1.48.0 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      id: toolchain
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Cargo cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}-${{ steps.toolchain.outputs.rustc_hash }}
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Install Cargo cache
      uses: actions-rs/install@v0.1
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        crate: cargo-cache
        use-tool-cache: true
    - name: Cleanup cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo cache -a
    - name: Cleanup windows cache
      if: steps.cache.outputs.cache-hit != 'true' && matrix.platform == 'windows-latest'
      shell: bash
      run: |
        rm -rf ~/.cargo/git/checkouts
        rm -rf ~/.cargo/registry/index
  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Install Tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        use-tool-cache: true
    - name: Generate coverage
      run: cargo tarpaulin --workspace --release --verbose --all-features --out Xml --timeout 120
    - name: Upload to Codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: cobertura.xml
